from typing import Any

from . import auto as auto

class tqdm:
    def __init__(self) -> None: ...
    def set_postfix(self, **kwargs: Any) -> None: ...
    def update(self, n: int = 1) -> None: ...
